Add retry and errors around failing to pull the vex report
Signed-off-by: Derek Nola <derek.nola@suse.com>

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -31,7 +31,15 @@ jobs:
           TAG=${{ env.TAG }}
 
     - name: Download Rancher's VEX Hub report
-      run: curl -fsSO https://raw.githubusercontent.com/rancher/vexhub/refs/heads/main/reports/rancher.openvex.json
+      run: |
+        curl -sfLOS --retry 3 https://github.com/rancher/vexhub/raw/refs/heads/main/reports/rancher.openvex.json || true
+        if (jq . rancher.openvex.json &> /dev/null); then
+            echo "Rancher's VEX report downloaded successfully"
+        else
+            echo "Failed to download Rancher's VEX report"
+            cat rancher.openvex.json
+            exit 1
+        fi
 
     - name: Run Trivy vulnerability scanner
       uses: aquasecurity/trivy-action@ed142fd0673e97e23eac54620cfb913e5ce36c25 # v0.36.0
